CREATE TABLE IF NOT EXISTS `Roles`(
`id` INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
`name` VARCHAR(20) NOT NULL UNIQUE,
`description` VARCHAR(100),
`is_active` TINYINT(1) DEFAULT 1,
`created` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)