CREATE TABLE IF NOT EXISTS `Users`(
    `id` INT AUTO_INCREMENT NOT NULL,
    `f_name` VARCHAR(25) NOT NULL,
    `middle_initial` CHAR(1),
    `l_name` VARCHAR(25) NOT NULL,
    `email_address` VARCHAR(100) NOT NULL UNIQUE,
    `password` VARCHAR(60) NOT NULL,
    `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `modified` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`)
)