CREATE TABLE IF NOT EXISTS `JobPosting` (
    `id` INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    `hr_id` INT NOT NULL,
    `title` VARCHAR(30) NOT NULL,
    `company_name` VARCHAR(50) NOT NULL,
    `location` VARCHAR(100) NOT NULL,
    `description` TEXT NOT NULL,
    `work_status` TINYINT(1) NOT NULL,
    `salary` VARCHAR(25) NOT NULL,
    `skills` JSON,
    `job_status` TINYINT(1) NOT NULL DEFAULT 1,
    `created` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `modified` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (`hr_id`) REFERENCES Employees(id)
);