CREATE TABLE IF NOT EXISTS `JobSettings` (
    `id` TINYINT(1) UNIQUE,
    `description` VARCHAR(50),
    `created` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `modified` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);